#!/bin/sh

if test "x$1" = "xclean"; then
    find . -name 'Makefile.in' -print0 | xargs -0r rm -f
    rm -rf autom4te.cache ChangeLog.* stamp-h* config.h.in* build-stamp aclocal.m4
    exit 0
fi

aclocal && 
autoheader &&
automake --gnu --add-missing --copy &&
autoconf
