.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GLSNAKE 6 "December 5, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
glsnake \- hardware accelerated executive stress toy.
.SH SYNOPSIS
.B glsnake
.RI
.SH DESCRIPTION
.B glsnake
is an imitation of Rubiks\' Snake, using OpenGL.
.PP
.SH INTERACTIVE COMMANDS
The right mouse button can be used to drag the object to a new
orientation.
.TP
.B ESC q
Quit.
.TP
.B f
Toggle between full-screen and windowed mode.
.TP
.B t
Toggle displaying of model titles.
.TP
.B w
Toggle wireframe mode on and off.
.TP
.B a
Toggle between two standard colour schemes.
.TP
.B e E
Change the explode distance.
.TP
.B + -
Change the speed of rotation.
.TP
.B . ,
Change to the next and previous models.
.TP
.B i
Enter interactive mode.
.br
In interactive mode, the cursor keys can be used to select a joint and
rotate it.  The home key resets to the straight snake.
.TP
.B d
Dump the current model.
.br
Dumps a description of the current model to stdout, in a format that can
be easily inserted into glsnake.
.SH BUGS
The snake will happily intersect itself while morphing (this is not a bug).
.br
.sp 1
Rotating the object with the mouse is only defined whilst the mouse pointer is
within an ellipse circumscribing the 4 corners of the window.  If you release
the mouse button whilst dragging out of this window, you may not be able to
recover the model without quitting.
.br
.sp 1
There are No Flocking Algorithms.
.SH AUTHOR
.B glsnake
was written by Jamie Wilkinson
.nh
<jaq@spacepants.org>,
.hy
Andrew Bennetts
.nh
<andrew@puzzling.org>
.hy
and Peter Aylett
.nh
<peter@ylett.com>.
.hy
.sp 1
This manual page was written by Peter Hardy
.nh
<peterhardy@pacific.net.au>,
.hy
who spent the entire time wondering exactly why he was writing it,
and Jamie Wilkinson, for the Debian GNU/Linux system (but may be
used by others).
