name: CI
on: [push,pull_request]
jobs:
  test:
    strategy:
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install -y scons libgl1-mesa-dev freeglut3-dev ${{ matrix.compiler }}
      - name: build
        run: scons
